a = 24
b = 4
amount = a + b
print ("amount =", a + b )
different = a - b
print ( "different = ", a - b)
multiplicatian = a * b
print ("multiplicatian =", a * b)
division = a / b
print ("division = ", a / b)
degree = a**b
print ("degree = ", a ** b)